version: 0.2

# env:
#  variables:
#   key: "value"
#    key: "value"
#  parameter-store:
#    key: "value"
#    key: "value"

phases:
#  install:
#    commands:
#      - command
#      - command
#    finally:
#      - command
#      - command
  pre_build:
    commands:
#      - command
#      - command
#    finally:
#      - command
#      - command
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew jacocoTestReport
#    finally:
#      - command
#      - command
  post_build:
    commands:
      - echo Build completed on `date`
#      - command
#    finally:
#      - command
#      - command
artifacts:
  files:
    - build/libs/movietracking-1.0.1.jar
#    - location
#    - name
#  discard-paths: yes
#  base-directory: location
#  secondary-artifacts:
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      discard-paths: yes
#      base-directory: location
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      discard-paths: yes
#      base-directory: location
#cache:
#  paths:
#    - path
#    - path
